ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080
    #port: ${?PORT}
  database:
    url: "jdbc:postgresql://localhost:5432/embly_backend"
    driver: "org.postgresql.Driver"
    user: "naruto"
    password: "naruto@305"
